#!/bin/bash
# Perform runtime initialization of container and update the 
# /opt/zimbra/qa/global.properties with proper configuration
# Expects the following envirnment variables:
#   ZIMBRA_HOST
#   ZIMBRA_DOMAIN
#   ZIMBRA_PASSWORDS

# Update the config file
echo "updating config"
sed -i.bak -e "s/localhost/${ZIMBRA_HOST}/" -e "s/zimbra\.com/${ZIMBRA_DOMAIN}/" -e "s/test123/${ZIMBRA_PASSWORDS}/" /opt/qa/soapvalidator/conf/global.properties
# Fire up STAF
export PATH=/usr/local/staf/bin:$PATH
echo 'PATH=/usr/local/staf/bin:$PATH' >> /root/.bashrc
echo "starting STAF"
/usr/local/staf/startSTAFProc.sh
sleep 5
echo "adding STAF services"
STAF local service add service SOAP LIBRARY JSTAF EXECUTE /opt/qa/soapvalidator/bin/zimbrastaf.jar
STAF local service add service LOG LIBRARY STAFLog
STAF LOCAL soap EXECUTE ${ZIMBRA_HOST} ZIMBRAQAROOT /opt/qa/soapvalidator/ DIRECTORY  /opt/qa/soapvalidator/data/soapvalidator/SanityTest/ LOG /results/ SUITE SANITY
