#!/bin/bash
# Run the image zimbra/soap-harness:latest, passing in the appropriate
# settings

DP=$(dirname $0)
EF="${DP}/.env"

if [ ! -f "${EF}" ]
then
    echo "Please copy DOT-env to ${EF} and update as necessary. Then re-run this script."
    exit 1
fi
. "${EF}"
docker run --network ${DOCKER_NETWORK} \
  --name soap \
  --dns ${DOCKER_DNS} --dns 8.8.8.8 \
  --hostname soap.test \
  --env-file "${EF}" \
  -dit zimbra/soap-harness:latest /opt/qa/init

