#!/bin/bash
# Run the image zimbra/soap-harness:latest, passing in the appropriate
# settings

DP=$(dirname $0)
pushd "${DP}"
ABS=$(pwd)
popd

EF="${DP}/.env"

if [ ! -f "${EF}" ]
then
    echo "Please copy DOT-env to ${EF} and update as necessary. Then re-run this script."
    exit 1
fi
. "${EF}"


docker run --network ${DOCKER_NETWORK} \
  --name soap \
  -v "${ABS}/results":/results \
  --dns ${DOCKER_DNS} --dns 8.8.8.8 \
  --hostname soap.test \
  --env-file "${EF}" \
  --rm \
  zimbra/soap-harness:latest

